;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Scissors",DevComment="")
+GameplayTagList=(Tag="Dialogue.Choice",DevComment="")
+GameplayTagList=(Tag="Quests",DevComment="")
+GameplayTagList=(Tag="Quests.tes2",DevComment="")
+GameplayTagList=(Tag="Quests.tes2.1",DevComment="")
+GameplayTagList=(Tag="Quests.tes2.2",DevComment="")
+GameplayTagList=(Tag="Quests.tes2.3",DevComment="")
+GameplayTagList=(Tag="Quests.Test",DevComment="")
+GameplayTagList=(Tag="Quests.Test.loc1",DevComment="")
+GameplayTagList=(Tag="Quests.Test.loc2",DevComment="")
+GameplayTagList=(Tag="Quests.Test.loc3",DevComment="")

